name: Setup COBOL

on: push

jobs:
  setup:
    name: GNUCOBOL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: fabasoad/setup-cobol-action@main
      - name: HW
        run: |
          cobc -x hw.cob
          ./hw
      - name: Retrieve Submodules
        run: |
          git submodule init
          git submodule update
      - name: Test
        run: |
          make test
